---
# Tailscale mesh VPN configuration

- name: Configure Tailscale
  when:
    - networking_tailscale_state == 'present'
    - vault_tailscale_oauth_workstation is defined
  become: true
  block:
    - name: Enable Tailscale with OAuth
      ansible.builtin.include_role:
        name: artis3n.tailscale.machine
      vars:
        tailscale_authkey: "{{ vault_tailscale_oauth_workstation.client_secret }}"
        tailscale_tags:
          - "workstation"
        tailscale_oauth_ephemeral: false
        tailscale_operator: "{{ primary_user }}"
        tailscale_args: >-
          --hostname={{ inventory_hostname }}
          --accept-routes={{ 'true' if networking_tailscale_accept_routes else 'false' }}
          --operator={{ primary_user }}

    - name: Ensure operator is set
      ansible.builtin.command:
        cmd: tailscale set --operator={{ primary_user }}
      changed_when: false

- name: Remove Tailscale
  when: networking_tailscale_state == 'absent'
  become: true
  block:
    - name: Disable Tailscale service
      ansible.builtin.systemd_service:
        name: tailscaled
        enabled: false
        state: stopped
      register: networking_tailscale_service_absent
      failed_when: false

    - name: Remove Tailscale package
      ansible.builtin.dnf:
        name: tailscale
        state: absent
