---
# Google Chrome

- name: Configure Google Chrome
  become: true
  block:
    - name: Add Google Linux packages GPG key
      ansible.builtin.rpm_key:
        state: "{{ 'present' if desktop_chrome_state == 'present' else 'absent' }}"
        key: "{{ desktop_chrome_repo_key }}"

    - name: Configure Google Chrome repository
      ansible.builtin.yum_repository:
        name: google-chrome
        file: google-chrome
        description: Google Chrome
        baseurl: "{{ desktop_chrome_repo_baseurl }}"
        enabled: "{{ desktop_chrome_state == 'present' }}"
        gpgcheck: true
        gpgkey: "{{ desktop_chrome_repo_key }}"
        state: "{{ desktop_chrome_state }}"

    - name: Install Google Chrome
      ansible.builtin.dnf:
        name: "{{ desktop_chrome_package }}"
        state: "{{ desktop_chrome_state }}"
