---
# Desktop applications

- name: Install desktop packages
  become: true
  block:
    - name: Install general desktop packages
      ansible.builtin.dnf:
        name: "{{ desktop_general_packages }}"
        state: present

    - name: Install desktop support packages
      ansible.builtin.dnf:
        name: "{{ desktop_support_applications }}"
        state: present

- name: Configure VS Code
  ansible.builtin.import_tasks: vscode.yml
  tags: [vscode]

- name: Configure Google Chrome
  ansible.builtin.import_tasks: chrome.yml
  tags: [chrome]

- name: Configure Vivaldi
  ansible.builtin.import_tasks: vivaldi.yml
  tags: [vivaldi]

- name: Configure AI desktop applications
  ansible.builtin.import_tasks: ai.yml
  tags: [ai]
