---
# Vivaldi

- name: Configure Vivaldi
  become: true
  block:
    - name: Add Vivaldi GPG key
      ansible.builtin.rpm_key:
        state: "{{ 'present' if desktop_vivaldi_state == 'present' else 'absent' }}"
        key: "{{ desktop_vivaldi_repo_key }}"

    - name: Configure Vivaldi repository
      ansible.builtin.yum_repository:
        name: vivaldi
        file: vivaldi
        description: Vivaldi
        baseurl: "{{ desktop_vivaldi_repo_baseurl }}"
        enabled: "{{ desktop_vivaldi_state == 'present' }}"
        gpgcheck: true
        gpgkey: "{{ desktop_vivaldi_repo_key }}"
        state: "{{ desktop_vivaldi_state }}"

    - name: Install Vivaldi
      ansible.builtin.dnf:
        name: "{{ desktop_vivaldi_package }}"
        state: "{{ desktop_vivaldi_state }}"
