---
# Visual Studio Code

- name: Configure Visual Studio Code
  become: true
  block:
    - name: Add Microsoft GPG key
      ansible.builtin.rpm_key:
        state: "{{ 'present' if desktop_vscode_state == 'present' else 'absent' }}"
        key: "{{ desktop_vscode_repo_key }}"

    - name: Configure Visual Studio Code repository
      ansible.builtin.yum_repository:
        name: vscode
        file: vscode
        description: Visual Studio Code
        baseurl: "{{ desktop_vscode_repo_baseurl }}"
        enabled: "{{ desktop_vscode_state == 'present' }}"
        gpgcheck: true
        gpgkey: "{{ desktop_vscode_repo_key }}"
        state: "{{ desktop_vscode_state }}"

    - name: Install Visual Studio Code
      ansible.builtin.dnf:
        name: "{{ desktop_vscode_package }}"
        state: "{{ desktop_vscode_state }}"
