opentofu:
    statePassphrase: ENC[AES256_GCM,data:jFV/fyiDFK5ubmFT7Fv1xBTi4TWdKECytn7QmlCtr+IE3XOnazU7G1NWn7KEfazoDnzJ9XwSPnCKD6TUvgy2hbk=,iv:0Av+6tDKShWbsKhbTlajEP1p879HfKSg7vMAbGpQwtA=,tag:DZywgJpAPX8YbCaHq02I6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN1ZMdXo5SDN5VXVUeXE1
            WGtLS2d5Tm1Na3JGakVJT0tLNzVUNm92eUhjCmJXUXpldUdsNEY5Tm1GVVFMdXRU
            YnhMRHFPMUd2eG4rN1VRK0FxbkRVSGMKLS0tIFRMUEFpQlM4Y2d5TVNjMlU3WjVG
            enF5akFJb2xVajFFQ0pZa1JGcWdHWWMKnAn/glPnSyeEQy50+boH25+eY4rmhB9+
            wZT3PQtQvL8ihpGqs7HYoHGcNTbwSsUJTHELduVfAU+CNk908idpUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aph83gkdg83l6cf83nsdthp95dcd5natpa7527sd3p8rtlcj3dgstl502c
    lastmodified: "2026-08-31T14:22:36Z"
    mac: ENC[AES256_GCM,data:ycYq+A6D9YHdLleSTgPfQ3dv8S1orFd1mDdBFkm+ebjzGHZm2BaV64udw/Nu5vgTBWyRYnU2vQJdsEKWSVoe26br3PJ2X5wzaHOic7l7nziCCPWykSbEL5klh8X0qwk8peClqjxUmGCLonLiEOp0ouD0uI6vIjE0eZUVR9dbXio=,iv:gBPbG9qsz7OD/sRmN/kTw77uZopacUiauHwmb3qux1k=,tag:n2tK0XhE3pjrRUwY46jbTg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
