---
# Resticprofile - system-level backup management

- name: Validate resticprofile configuration
  ansible.builtin.assert:
    that:
      - backup_resticprofile_state in ["present", "absent"]
      - backup_resticprofile_archive_sha256 | length == 64
    quiet: true

- name: Load vault secrets
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/vault.yml"
  when:
    - backup_resticprofile_state == 'present'
    - backup_resticprofile_configure_enabled | bool
  no_log: true

- name: Resticprofile setup
  become: true
  block:
    - name: Install resticprofile
      ansible.builtin.include_tasks: install.yml
      when: backup_resticprofile_state == 'present'

    - name: Configure resticprofile
      ansible.builtin.include_tasks: configure.yml
      when:
        - backup_resticprofile_state == 'present'
        - backup_resticprofile_configure_enabled | bool

    - name: Uninstall resticprofile
      ansible.builtin.include_tasks: uninstall.yml
      when: backup_resticprofile_state == 'absent'
