---
- name: Validate sync tools configuration
  ansible.builtin.assert:
    that:
      - sync_tools_state in ["present", "absent"]
      - sync_tools_mega_state in ["present", "absent"]
      - sync_tools_insync_state in ["present", "absent"]
    quiet: true

- name: Configure Fedora-native sync tools
  ansible.builtin.include_tasks: native.yml

- name: Configure MEGA sync tools
  ansible.builtin.include_tasks: mega.yml

- name: Configure Insync sync tools
  ansible.builtin.include_tasks: insync.yml
