opentofu:
    statePassphrase: ENC[AES256_GCM,data:HqvunuZsr8zj26ajY59hfJ3fSKlthj/3n7dh7PHMwPUwjVE+gAa4N+n80nAtbs9yo9exoDm1M0hisKbWD9e2MaY=,iv:ZUpdt4OH3AOT/xwnTRdJKIP69pMXW3kgvOTlMuFvEeg=,tag:lBoCRNHgfOTOfK4uzCAK0g==,type:str]
credentials:
    management:
        accessKeyId: ENC[AES256_GCM,data:8bsT8VtdREKzchZhR0SS0WzRUC8=,iv:/ARuknE5d+xKw8Apv/cqgo+PcAl1TZZFl16rKMM8nMw=,tag:JSqvDjo4MhA+UcEM2U19VQ==,type:str]
        secretAccessKey: ENC[AES256_GCM,data:RXVA2nWt7yp+Aj4ixahRqjDzkdAaLTqKlGzIvUuZr6f0hwPy,iv:alV0YJR+3QhfzASQjatdbmuoJSJuvrW53KnbGMTnjTc=,tag:UkXiiFj5DtUHskzd/mzkfQ==,type:str]
backend:
    scaleway:
        accessKeyId: ENC[AES256_GCM,data:mwLgwRzmP+a/TTSfpiLQSiLKMxc=,iv:TINWaG0bsq6UUTuJiQpgmoA/eOFOb345m2y3EeYE+Bc=,tag:qcyKZwphLzOzVFWvfME2UQ==,type:str]
        secretAccessKey: ENC[AES256_GCM,data:DWlz4DvBkx8q/pAlpUvEO7ChIq1gcueJsVV9ieIlaJYZqMte,iv:nxkl9eoLz8iOT1A8o8Z3Vu3lGagTPqZufQI70IaNljI=,tag:zt4E+IV7SU0g3zWWbG2+qg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdG9wSTd6QjZ6elpmUkVW
            YXdHUmdMQTB6VUhFeTk2Z21pRXJFS0lwMlRJCitQQ0RNcnhOdkV4K0IzT1hvUlFN
            dndYSTdrZkJSNkZ1ZXBhL3dBM3J4elkKLS0tIFJiWmVZbkpwUDRKUmFMYTY1WDU2
            UDA5Q0E5c2REZ0RJbG1YZ0lQYitwTWcKL1sjE2D0Rf2RuqosghtM8FqLe6lPjSnL
            LfWNVpIb4luANCWZ2nZdc3U7jmVeCoJxKxfiL1vJI46WCsUbV1dCRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aph83gkdg83l6cf83nsdthp95dcd5natpa7527sd3p8rtlcj3dgstl502c
    lastmodified: "2026-08-31T14:26:36Z"
    mac: ENC[AES256_GCM,data:FoYEJc2J5wM2EwyarMFHNLuowFEdNhvY5zlGrAfQRNM1LVu7mTRyNXVv/PQCricVeUM4drYVGUc4sPNsJ4Tujb++N2etgFDWuJ1JEcyiqE8ipcYY9uGwhkhFI7/kc+GSC6VMpOwLZzHxeMRI+EwkGsU94AH6Flaa25rklndQEVA=,iv:kDeeOPpGNzNo8Cy9ZcILPN3MkNmM9naxMDDPgwYgrcY=,tag:6a/tpz7/NZQTL+lZy2hGmg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
