---
- name: Install base packages
  become: true
  block:
    - name: Install system utilities
      when: base_system_utils | length > 0
      ansible.builtin.dnf:
        name: "{{ base_system_utils }}"
        state: present

    - name: Install CLI tools
      when: base_cli_utils | length > 0
      ansible.builtin.dnf:
        name: "{{ base_cli_utils }}"
        state: present

    - name: Install host-specific extra packages
      when: base_extra_packages | length > 0
      ansible.builtin.dnf:
        name: "{{ base_extra_packages }}"
        state: present
