---
- name: Configure user tmpfiles rules
  become: true
  block:
    - name: Ensure /usr/lib/user-tmpfiles.d exists
      ansible.builtin.file:
        path: /usr/lib/user-tmpfiles.d
        state: directory
        mode: "0755"

    - name: Deploy user tmpdir tmpfiles.d rule
      ansible.builtin.copy:
        src: tmpfiles.d/user-tmpdir.conf
        dest: /usr/lib/user-tmpfiles.d/user-tmpdir.conf
        mode: "0644"
